# Generated by Django 3.1.5 on 2021-01-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210116_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='hue1',
            field=models.PositiveSmallIntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='image',
            name='hue2',
            field=models.PositiveSmallIntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='image',
            name='hue3',
            field=models.PositiveSmallIntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='image',
            name='hue4',
            field=models.PositiveSmallIntegerField(default=10000),
        ),
    ]
